esphome:
  name: lanontvangera
  friendly_name: lanontvangerA

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "B7gCt19UngnsY442CJu7YrI81byTEju9FXVyrfh07qU="

ota:
  - platform: esphome
    password: "8025954462073d1f7ce6631703d65618"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16


#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Lanzender Fallback Hotspot"
#    password: "kipkipkip"

#captive_portal:


web_server:
  port: 80


udp:
  update_interval : 10ms
  binary_sensors:
    - relay14a_tm  #wat broadcast je



switch:
  - platform: gpio
    pin: GPIO14
    id: relay14a
    name: "relay 14a switch"

binary_sensor:
  - platform: template
    id: relay14a_tm
    lambda: "return id(relay14a).state;"

 
##binary sensors afkomstig vd zender
  - platform: udp
    provider: lanzender
    id: knop14
    on_press:
      switch.turn_on: relay14a
    on_release:
      switch.turn_off: relay14a      