esphome:
  name: lanontvangerb
  friendly_name: lanontvangerB
#https://github.com/v12345vtm/webrelais-webinput
esp32:
  board: esp32dev
  framework:
    type: arduino
 


# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s #we werken zonder homeassistant en anders reboot de esp na 15minuten
  
ota:
  - platform: esphome
    password: "8025954462073d1f7ce6631703d65618"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16


#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Lanzender Fallback Hotspot"
#    password: "kipkipkip"

#captive_portal:

web_server:
  port: 80



button:
  - platform: restart
    name: "Restart Device"
    entity_category: diagnostic
    icon: mdi:restart

#text_sensor:
#  - platform: ethernet_info    
#    ip_address:
#      name: "ontvangerA IP Address"
#      id : ontvangerAip


udp:
  update_interval : 10ms
  binary_sensors:
    - relay14b_tm  #wat broadcast je 
    - relay15b_tm  #wat broadcast je 





switch:
  - platform: gpio
    pin: GPIO14
    id: relay14b #dit is onze fysyke relais
    name: "relay 14b switch"
    inverted: True


  - platform: gpio
    pin: GPIO15
    id: relay15b #dit is onze fysyke relais
    name: "relay 15b switch"
    inverted: True

binary_sensor:
  - platform: template
    id: relay14b_tm #dit dient om status vd webrelais te vragen en dan tm sturen nr zender
    lambda: "return id(relay14b).state;"


  - platform: template
    id: relay15b_tm #dit dient om status vd webrelais te vragen en dan tm sturen nr zender
    lambda: "return id(relay15b).state;"    

##binary sensors afkomstig vd zender
  - platform: udp
    provider: lanzender
    id: knop14
    on_press:
      switch.turn_on: relay14b
    on_release:
      switch.turn_off: relay14b     


##binary sensors afkomstig vd zender
  - platform: udp
    provider: lanzender
    id: knop15
    on_press:
      switch.turn_on: relay15b
    on_release:
      switch.turn_off: relay15b     