esphome:
  name: lanontvangera
  friendly_name: lanontvangerA
 


#https://github.com/v12345vtm/webrelais-webinput
esp32:
  board: esp32dev
  framework:
    type: arduino
 


# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s #we werken zonder homeassistant en anders reboot de esp na 15minuten
    
#  encryption:
#    key: "B7gCt19UngnsY442CJu7YrI81byTEju9FXVyrfh07qU="

button:
  - platform: restart
    name: "Restart Device"
    entity_category: diagnostic
    icon: mdi:restart


ota:
  - platform: esphome
    password: "8025954462073d1f7ce6631703d65618"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16


#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Lanzender Fallback Hotspot"
#    password: "kipkipkip"

#captive_portal:

web_server:
  port: 80


#text_sensor:
#  - platform: ethernet_info    
#    ip_address:
#      name: "ontvangerA IP Address"
#      id : ontvangerAip


udp:
  update_interval : 10ms
  binary_sensors:
    - relay14a_tm  #wat broadcast je 
    - relay15a_tm  #wat broadcast je 
 
 

switch:
  - platform: gpio
    pin: GPIO14
    id: relay14a #dit is onze fysyke relais
    name: "relay 14a switch"
    inverted: True


  - platform: gpio
    pin: GPIO15
    id: relay15a #dit is onze fysyke relais
    name: "relay 15a switch"
    inverted: True

binary_sensor:
  - platform: template
    id: relay14a_tm #dit dient om status vd webrelais te vragen en dan tm sturen nr zender
    lambda: "return id(relay14a).state;"


  - platform: template
    id: relay15a_tm #dit dient om status vd webrelais te vragen en dan tm sturen nr zender
    lambda: "return id(relay15a).state;"    

##binary sensors afkomstig vd zender
  - platform: udp
    provider: lanzender
    id: knop14
    on_press:
      switch.turn_on: relay14a
    on_release:
      switch.turn_off: relay14a      


##binary sensors afkomstig vd zender
  - platform: udp
    provider: lanzender
    id: knop15
    on_press:
      switch.turn_on: relay15a
    on_release:
      switch.turn_off: relay15a        