esphome:
  name: lanzender
  friendly_name: lanzender

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "mkwhArJIHvLLtkw+bZj9rndSOOBEWs7q/KY5rhcVfAQ="

ota:
  - platform: esphome
    password: "bc3813fa98e6d2d9b271924c4548192b"


ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16


#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Lanzender Fallback Hotspot"
#    password: "kipkipkip"

#captive_portal:

web_server:
  port: 80



 

udp:
  update_interval: 10ms
  binary_sensors:
    - knop14

 

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: True
      mode: INPUT_PULLUP
    name: "knop veertien"
    id : knop14

  - platform: template
    name: "knop veertien tm"
    id: knop14tm
    lambda: "return id(relay14a_tm).state;"

  - platform: udp
    provider: lanontvangera
    id: relay14a_tm #id van de tm vd onvanger
    on_press:
      - binary_sensor.template.publish:
          id: knop14tm
          state: ON
    on_release:
      - binary_sensor.template.publish:
          id: knop14tm
          state: OFF

